### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Coffined** [SexuallyAbusive/Zyklon#48]
OS : Windows 10
JDK : Latest
Node.js : Latest
Error is below :
Starting cloud configuration server.
Visit http://localhost:1337 on your machine or http://192.168.x.x:1337 on an external device to use it.
node:events:353
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1337
    at Server.setupListenHandle [as _listen2] (node:net:1295:16)
    at listenInCluster (node:net:1343:12)
    at Server.listen (node:net:1429:7)
    at Function.listen (C:\Users\19173\Desktop\Random\bin\cloud\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\19173\Desktop\Random\bin\cloud\app.js:109:5)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1322:8)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 1337
}

**Comment by SexuallyAbusive** [comment]
you probably use razer software, which uses port 1337

just change the localhost port to something else, like 1338

**Comment by Coffined** [comment]
ook ty
